package com.herokuapp.automation;

import org.testng.TestException;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
        int num[];
        int num1[]= new int[8];
        int test[]=new int [7];
        int []myScores[];
        int[] myTest[];
        int [] myTest1;

        float f1 = -343;
        float f2 = -343;
        float f3 = 0x12345;
        //float f4 = 42e7;
        //float f5 = 2001.0D;
        float f6 = 2.81F;


        System.out.println('a'+9+3+"pritam"+10+20);
        System.out.println('A'+0+'B'+"A");
        System.out.println('a'+"");
        System.out.println('a'+"A");
        System.out.println("A"+'a');
        System.out.println('a'+'b'+"A");
        System.out.println('a');



    }

    class TestException extends Exception {}
    public void runTest() {}
    public void test()  /* Point X */
    {
        runTest();
    }
}
